import { useEffect } from 'react'
import { Link } from 'react-router-dom'

export default function Terms() {
  useEffect(() => {
    document.title = 'Terms of Service — FedBenefitsAid'
    window.scrollTo(0, 0)
  }, [])

  return (
    <main style={styles.main}>
      <div style={styles.container}>
        <h1 style={styles.h1}>Terms of Service</h1>
        <p style={styles.updated}>Last updated: April 7, 2026</p>

        <section style={styles.section}>
          <h2 style={styles.h2}>1. Acceptance of Terms</h2>
          <p style={styles.p}>
            By accessing and using fedbenefitsaid.com, you agree to be bound by these Terms of Service. If you do not agree to these terms, please do not use this website. You must be at least 18 years of age to use FedBenefitsAid.
          </p>
        </section>

        <section style={styles.section}>
          <h2 style={styles.h2}>2. Description of Service</h2>
          <p style={styles.p}>
            FedBenefitsAid provides educational tools and informational resources about federal employee retirement benefits, including FERS pension, TSP, FEHB, FEGLI, Social Security, and the FERS Supplement. Our platform offers:
          </p>
          <ul style={styles.list}>
            <li>Retirement calculator for estimating FERS pension benefits</li>
            <li>AI chat assistant for answering federal benefits questions</li>
            <li>Retirement readiness assessment (12-question quiz)</li>
            <li>Reference guides and educational content</li>
            <li>Free consultation booking through Calendly</li>
          </ul>
        </section>

        <section style={styles.section}>
          <h2 style={styles.h2}>3. NOT Financial or Legal Advice</h2>
          <p style={styles.p}>
            FedBenefitsAid provides informational and educational content only. Nothing on this website constitutes personalized financial advice, investment advice, tax advice, or legal advice. By using our tools and resources, you understand that:
          </p>
          <ul style={styles.list}>
            <li>Calculator results are estimates based on user-provided inputs and publicly available formulas. Actual benefits may differ from estimates.</li>
            <li>AI chat responses are generated by artificial intelligence and may contain errors or outdated information. AI responses should never be treated as official advice.</li>
            <li>You should consult qualified financial advisors, tax professionals, or attorneys for personalized advice tailored to your situation.</li>
            <li>You can verify critical information directly with the Office of Personnel Management (OPM) at opm.gov.</li>
          </ul>
          <p style={styles.p}>
            FedBenefitsAid is not affiliated with OPM, the U.S. government, or any federal agency.
          </p>
        </section>

        <section style={styles.section}>
          <h2 style={styles.h2}>4. User Accounts</h2>
          <p style={styles.p}>
            If you create an account on FedBenefitsAid, you agree to:
          </p>
          <ul style={styles.list}>
            <li>Provide accurate and complete information during registration</li>
            <li>Maintain the confidentiality of your password and account credentials</li>
            <li>Notify us immediately of any unauthorized access to your account</li>
            <li>Accept responsibility for all activities that occur under your account</li>
          </ul>
          <p style={styles.p}>
            We reserve the right to suspend or terminate accounts that violate these terms or engage in prohibited activities.
          </p>
        </section>

        <section style={styles.section}>
          <h2 style={styles.h2}>5. Consultations</h2>
          <p style={styles.p}>
            Free consultations are booked through Calendly and conducted by Federal Market Associates, a separate financial consulting firm. You understand that:
          </p>
          <ul style={styles.list}>
            <li>FedBenefitsAid connects you with Federal Market Associates but does not employ their advisors directly</li>
            <li>Consultations are educational in nature and do not establish a fiduciary relationship unless a formal advisory agreement is executed</li>
            <li>Any advice given during consultations is general in nature and the responsibility of the consulting firm and advisor providing it</li>
          </ul>
        </section>

        <section style={styles.section}>
          <h2 style={styles.h2}>6. Intellectual Property</h2>
          <p style={styles.p}>
            All content, tools, designs, code, and materials on fedbenefitsaid.com are owned by or licensed to FedBenefitsAid. This includes:
          </p>
          <ul style={styles.list}>
            <li>The retirement calculator and assessment tools</li>
            <li>Reference data and educational content</li>
            <li>Website design, layout, and user interface</li>
            <li>All proprietary formulas and algorithms</li>
          </ul>
          <p style={styles.p}>
            You may not copy, modify, distribute, or create derivative works without express written permission. Unauthorized use of our intellectual property is prohibited.
          </p>
        </section>

        <section style={styles.section}>
          <h2 style={styles.h2}>7. Limitation of Liability</h2>
          <p style={styles.p}>
            FedBenefitsAid is provided "as is" without warranties of any kind, either expressed or implied. To the fullest extent permitted by law, FedBenefitsAid is not liable for:
          </p>
          <ul style={styles.list}>
            <li>Any damages arising from your use of the site, tools, or information provided</li>
            <li>Financial losses, missed benefits, or incorrect decisions based on calculator results or AI chat responses</li>
            <li>Errors, omissions, or inaccuracies in the information provided</li>
            <li>Interruptions in service or technical issues with the website</li>
          </ul>
          <p style={styles.p}>
            Your maximum liability against FedBenefitsAid is limited to zero dollars, as the service is provided free of charge.
          </p>
        </section>

        <section style={styles.section}>
          <h2 style={styles.h2}>8. Accuracy of Information</h2>
          <p style={styles.p}>
            We strive to keep all information current based on 2026 federal retirement data. However, federal benefit rules, regulations, and rates can change at any time. FedBenefitsAid is not responsible for:
          </p>
          <ul style={styles.list}>
            <li>Changes in federal law or regulations that occur after information is posted</li>
            <li>Errors, omissions, or outdated information</li>
            <li>Discrepancies between our information and official government sources</li>
          </ul>
          <p style={styles.p}>
            You should verify critical information with official government sources such as OPM.gov, IRS.gov, or SSA.gov before making important benefit decisions.
          </p>
        </section>

        <section style={styles.section}>
          <h2 style={styles.h2}>9. Third-Party Services</h2>
          <p style={styles.p}>
            FedBenefitsAid uses various third-party services including Supabase, Airtable, Anthropic, Calendly, and Netlify. We are not responsible for:
          </p>
          <ul style={styles.list}>
            <li>The availability, accuracy, or functionality of third-party services</li>
            <li>Data loss or security breaches involving third parties</li>
            <li>Third-party terms of service or privacy policies</li>
          </ul>
          <p style={styles.p}>
            Your use of third-party services is subject to their respective terms and conditions.
          </p>
        </section>

        <section style={styles.section}>
          <h2 style={styles.h2}>10. Prohibited Uses</h2>
          <p style={styles.p}>
            You agree not to use FedBenefitsAid for any of the following purposes:
          </p>
          <ul style={styles.list}>
            <li>Attempting to gain unauthorized access to the site or its systems</li>
            <li>Using automated tools, bots, or scrapers to harvest data</li>
            <li>Impersonating others or providing false information</li>
            <li>Using the service for any illegal, fraudulent, or harmful purpose</li>
            <li>Violating any applicable laws or regulations</li>
          </ul>
        </section>

        <section style={styles.section}>
          <h2 style={styles.h2}>11. Modifications to Terms</h2>
          <p style={styles.p}>
            FedBenefitsAid reserves the right to modify these terms at any time. We will update the "Last updated" date when changes are made. Your continued use of the website after changes are posted constitutes your acceptance of the revised terms. We recommend reviewing these terms periodically.
          </p>
        </section>

        <section style={styles.section}>
          <h2 style={styles.h2}>12. Governing Law</h2>
          <p style={styles.p}>
            These Terms of Service are governed by and construed in accordance with the laws of the United States, without regard to its conflict of law provisions. Any legal action or proceeding shall be brought exclusively in the appropriate courts of the United States.
          </p>
        </section>

        <section style={styles.section}>
          <h2 style={styles.h2}>13. Contact Information</h2>
          <p style={styles.p}>
            If you have questions about these Terms of Service, please contact us:
          </p>
          <ul style={styles.list}>
            <li>Email: jhf17@icloud.com</li>
            <li>Website: fedbenefitsaid.com</li>
            <li>Schedule a consultation:{' '}
              <a href="https://calendly.com/jhf17/30min" target="_blank" rel="noopener noreferrer" style={styles.link}>
                calendly.com/jhf17/30min
              </a>
            </li>
          </ul>
        </section>

        <section style={styles.disclaimer}>
          <p style={styles.disclaimerText}>
            These terms are provided for transparency and informational purposes. We recommend consulting with a legal professional for specific legal questions or interpretations of these terms.
          </p>
        </section>

        <nav style={styles.backWrap}>
          <Link to="/" style={styles.backLink}>Back to Home</Link>
        </nav>
      </div>
    </main>
  )
}

const styles = {
  main: {
    minHeight: 'calc(100vh - 64px)',
    background: '#f8fafc',
    padding: '48px 0 80px',
  },
  container: {
    maxWidth: 720,
    margin: '0 auto',
    padding: '0 24px',
  },
  h1: {
    fontSize: 'clamp(1.6rem, 3vw, 2.2rem)',
    fontWeight: 800,
    color: '#0f172a',
    letterSpacing: '-0.02em',
    marginBottom: 4,
  },
  updated: {
    fontSize: '0.85rem',
    color: '#64748b',
    marginBottom: 40,
  },
  section: {
    marginBottom: 36,
  },
  h2: {
    fontSize: '1.15rem',
    fontWeight: 700,
    color: '#1e3a5f',
    marginBottom: 10,
  },
  p: {
    fontSize: '0.95rem',
    color: '#475569',
    lineHeight: 1.7,
    marginBottom: 12,
  },
  list: {
    fontSize: '0.95rem',
    color: '#475569',
    lineHeight: 1.7,
    marginBottom: 12,
    marginLeft: 24,
    listStyleType: 'disc',
  },
  link: {
    color: '#2563eb',
    textDecoration: 'none',
    fontWeight: 500,
  },
  disclaimer: {
    marginTop: 48,
    padding: 24,
    background: '#f1f5f9',
    borderRadius: 8,
    borderLeft: '4px solid #1e3a5f',
    marginBottom: 36,
  },
  disclaimerText: {
    fontSize: '0.9rem',
    color: '#475569',
    lineHeight: 1.6,
    margin: 0,
    fontStyle: 'italic',
  },
  backWrap: {
    marginTop: 48,
    paddingTop: 24,
    borderTop: '1px solid #e2e8f0',
  },
  backLink: {
    color: '#1e3a5f',
    fontWeight: 600,
    fontSize: '0.95rem',
    textDecoration: 'none',
  },
}
